### PR TITLE
Fix major API design/security flaw: Denial of service on large quantity of users

### PR DESCRIPTION
**Pull request by 20kdc**
The API's existence introduces a long-term denial-of-service attack against large classes of users, including but not limited to large classes of marginalized users.

Users who are running outdated devices will, over time, find themselves effectively "removed from the internet" where this API is applied.

We have seen similar effects on a smaller scale with the advent of Intel Secure Enclave hardware being *required* to view EME-protected content on certain media websites. However, those effects are limited to media, and particularly services willing to operate on that basis.

Such an API becoming available for general use in all contexts guarantees the effects becoming magnified across many types of content.

Marginalized users running outdated hardware *will* be affected.

Not to mention people who are simply trying to get more performance out of up to date, but weak hardware, in ways which cause the attestation to fail (Don't think I don't know where you got the term "Attestation" from. It's obviously going to involve Secure Enclave or equally overbearing system examination, particularly for the anticheat usecase).

Using Linux? No attestation; The kernel can't be trusted, after all.
Using Windows with drivers that don't fit the requirements? No attestation.
No TPM? No attestation.
No Secure Enclave? No attestation.

And so on.

This is a *logical guarantee* short of magical divine intervention, which as I hope you know, won't happen.

The only fix is deletion.

### CODE REVIEW

**Review by theseer — APPROVED** [review]

**Review by klrtk — APPROVED** [review]

**Review by mpldr — CHANGES_REQUESTED** [review]
I think a more detailed explanation on why this idea is a well-written declaration of war towards the open internet would be useful.

**Review by brendanno — APPROVED** [review]

**Review by Zumorica — APPROVED** [review]

**Review by BinBashBanana — APPROVED** [review]

**Review by Tau5 — APPROVED** [review]

**Review by perillamint — APPROVED** [review]

**Review by stop-treachery — APPROVED** [review]

**Review by Leo40Git — APPROVED** [review]
Can the internet stop self-destructing for TWO MINUTES

**Review by cybik — APPROVED** [review]

**Review by chfour — APPROVED** [review]

**Comment by cybik** [comment]
@Leo40Git ostensibly not.

**Review by comradef191 — APPROVED** [review]
Of course, the creators of this are affiliated with Google;
I'm sure you can work out the implications of _that_ yourself.

**Review by Nomz420 — APPROVED** [review]

**Pull request closed without merging**
