### PR TITLE
replace everything with my fursona

### PR DESCRIPTION
**Pull request by owocean**
i think this will really improve the whole thing

### CODE REVIEW

**Review by Capital-EX — APPROVED** [review]

**Review by nilsding — APPROVED** [review]

**Review by gitlimes — APPROVED** [review]
looks great to me :3

**Review by coricarson — APPROVED** [review]
🚢

**Review by Kusanalee — APPROVED** [review]

**Review by maj113 — CHANGES_REQUESTED** [review]
While I like the PR the jpeg should be replaced with a PNG

**Review by Nomz420 — APPROVED** [review]

**Review by adryzz — APPROVED** [review]

**Review by sirlan-ff00ff — APPROVED** [review]
cute 10/10

**Pull request closed without merging**
