### PR TITLE
fix: introduce alternate attestation API implementation (resolves #28)

### LINKED ISSUE #28: Don't.
Sometimes you have to ask the question whether something should be done at all, and trusted computing is certainly one of those cases where the answer is obviously a big fat NO.

So please reconsider what you believe in, leave this demon to history where it forever belongs.

### PR DESCRIPTION
**Pull request by gitlimes**
There's little I could say that probably hasn't already been said by other people in #28.

So here's something that definitely hasn't been said before:

hewwo googwe~
if it can math, i can twust~
so couwd you pweatty pwease not fuck us ovew wif youw buwwshit fow owonce? >:3
thanks :3

### CODE REVIEW

**Review by maj113 — APPROVED** [review]

**Review by Tau5 — APPROVED** [review]

**Review by mokrates — APPROVED** [review]
LGTM

**Review by Jack5079 — APPROVED** [review]

**Review by adryzz — APPROVED** [review]

**Review by joebobbio — APPROVED** [review]
lgtm

**Review by perillamint — APPROVED** [review]
LGTM

**Review by natep-tech — APPROVED** [review]

**Review by SteffoSpieler — APPROVED** [review]
lgtm

**Review by chfour — APPROVED** [review]
lgtm but minor nitpick: maybe we could just reduce it to a `const attestation = () => 1 + 1 === 2`? no need for the braces

**Comment by gitlimes** [comment]
> lgtm but minor nitpick: maybe we could just reduce it to a `const attestation = () => 1 + 1 === 2`? no need for the braces

that's a good idea! personally, i like using the curly braces for clarity, but we can always just let the website choose the preferred form, considering how little of a size difference there is between implementations

**Review by lunaneff — APPROVED** [review]

**Pull request closed without merging**
