### PR TITLE
Clarify language

### PR DESCRIPTION
**Pull request by ShittyKopper**
#28

### CODE REVIEW

**Review by perillamint — APPROVED** [review]
Fantastic!

**Review by kleinesfilmroellchen — APPROVED** [review]
LGTM

**Review by adryzz — APPROVED** [review]
lgtm

**Comment by diederikdehaas** [comment]
I think the file name extension is rather fitting: ``docs/spec.bs``

**Review by 2minwia — APPROVED** [review]
looks #swag to me

**Review by JulianHeuser — APPROVED** [review]

**Review by Arteneko — APPROVED** [review]

**Review by a1batross — APPROVED** [review]

**Review by nononymousse — APPROVED** [review]

**Review by theseer — APPROVED** [review]

**Review by natep-tech — APPROVED** [review]

**Review by JordanMatuschka — APPROVED** [review]

**Review by sparked435 — APPROVED** [review]

**Review by Written0489 — APPROVED** [review]

**Review by fautz — APPROVED** [review]

**Review by zyzzyxdonta — APPROVED** [review]
Shippit!

**Review by 4ndv — APPROVED** [review]

**Comment by mauke** [comment]
If the user
has squandered the confidence of the website
and could only win it back
by redoubled work, would it not in that case
be simpler for the website
to close the user
and visit another?

**Review by tylermurphy534 — APPROVED** [review]
looks good to me

**Review by ethanalker — APPROVED** [review]

**Review by wwahammy — APPROVED** [review]
Good correction, I support merging.

**Comment by coupcelle** [comment]
excellent self-documenting code, LGTM

**Review by mpldr — APPROVED** [review]
I think this clears it up very well.

**Review by dougfinnie — APPROVED** [review]
Much clearer on the intent, nice work.

**Review by Jack5079 — APPROVED** [review]

**Review by joebobbio — APPROVED** [review]

**Review by brendanno — APPROVED** [review]

**Review by lewisje — APPROVED** [review]
This change does clarify the true intent of the Web Environment Integrity proposal.

**Review by Zumorica — APPROVED** [review]

**Review by BinBashBanana — APPROVED** [review]

**Review by mc776 — APPROVED** [review]

**Review by Kuuuube — APPROVED** [review]

**Review by FranciscoPombal — APPROVED** [review]

**Review by Tau5 — APPROVED** [review]

**Review by uazo — APPROVED** [review]

**Review by ninelore — APPROVED** [review]

**Review by num13ru — APPROVED** [review]

**Review by TRezendes — APPROVED** [review]

**Review by monoxane — APPROVED** [review]
Excellent PR, The shareholders will love the additional value provided. LGTM.

**Review by Capital-EX — APPROVED** [review]

**Review by stop-treachery — APPROVED** [review]

**Review by cybik — APPROVED** [review]

**Review by rbos — APPROVED** [review]
Good clarification; no notes.

**Review by yerdua — APPROVED** [review]

**Review by chfour — APPROVED** [review]
yep lgtm

**Review by h3x4d3c1m4l — APPROVED** [review]

**Review by ThatOneCalculator — APPROVED** [review]
LGTM, ship it!

**Review by comradef191 — APPROVED** [review]

**Review by rugk — APPROVED** [review]

**Review by derickr — APPROVED** [review]

**Review by ryanw — APPROVED** [review]

**Review by ChineseMarc — APPROVED** [review]

**Review by HellyTubbies — APPROVED** [review]

**Review by owocean — APPROVED** [review]

**Review by coricarson — APPROVED** [review]

**Review by lunaneff — APPROVED** [review]

**Review by shiroeni — APPROVED** [review]

**Review by PaulusParssinen — APPROVED** [review]

**Pull request closed without merging**
